# This workflow will train and test detection model on self-hosted runner. It assumes system or local Python is configured on the host.

name: Create detection model

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install global dependencies
      run: pip install -r requirements.txt
    - name: Install model dependencies
      run: if [ -f content-classification/requirements.txt ]; then pip install -r content-classification/requirements.txt; fi
